version: '3'
services:
  flask:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: flask_container
    tty: true
    volumes:
      - ./:/usr/src
    ports:
      - "80:80"
  vue:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: vue_img
    container_name: vue_container
    tty: true
    volumes:
      - ./:/usr/src
    ports:
      - "8080:8080"