version: '2.4'
services:
  flask:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: flask_container
    tty: true
    volumes:
      - ./:/usr/src
    ports:
      - "5000:5000"
  vue:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: vue_img
    container_name: vue_container
    tty: true
    volumes:
      - ./:/usr/src
    ports:
      - "8080:8080"
  stylegan2:
    privileged: true
    tty: true
    build: 
      context: .
      dockerfile: ./backend/styleGan/Dockerfile
    image: stylegan2:latest
    container_name: 'StyleGAN2'
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./:/usr/src
    ports:
      - "80:80"